### ISSUE TITLE
Feature request: Trying to implement new Zirrfa 8x8x8 mono color

### ISSUE THREAD

**Issue by BaltasarParreira** [MajicDesigns/MD_Cubo#8]
I have this cube and works similar to the 4x4x4 that already exists except is not RGB.
It uses the same STC15f2k60s2 chip.
Did some changes and create new files but is not working yet so I'm looking for help.

Example code to manual put a zero on the front:

unsigned char mBuffer[64];
unsigned char Zero[16]          = {0x00, 0x7C, 0xFE, 0xB2, 0x9A, 0xFE, 0x7C, 0x00, 0x00, 0x7C, 0xFE, 0xB2, 0x9A, 0xFE, 0x7C, 0x00}; // 0

 for (int i=48;i<64;i++) {
    mBuffer[i] = Zero[i-48];
 }
 Serial.write(0xf2); 
 Serial.write(mBuffer,64);

I think the problem is how this cube has the led's addressed.

**Comment by c-schmitz** [comment]
Link to the kit on sale?

Usually the vendor provides at least a few lines of example code. Did you get that one to work?

**Comment by BaltasarParreira** [comment]
Yes, I have the vendor example and it works. 

I attached here the info/files I got from him.

Thanks.
[Arduino_3DCube_Control.zip](https://github.com/MajicDesigns/MD_Cubo/files/3026029/Arduino_3DCube_Control.zip)

**Comment by BaltasarParreira** [comment]
And here is the initial new cube version files I created.
Led's on the cube are moving a bit but no proper animations or anything as suppose to be as the animations description says. 

[MD_Cubo_8x8_STC.zip](https://github.com/MajicDesigns/MD_Cubo/files/3026134/MD_Cubo_8x8_STC.zip)

**Comment by c-schmitz** [comment]
I don't think writing an array of chars to the cube will work, as clearly an array of bytes is expected.
The letter animation is imho one of the harde things to solve - you should probably start with easier animations first and keep very close to the vendore example.

**Comment by BaltasarParreira** [comment]
The example I wrote here in the first post is working and puts the number zero character on the front as you can see in the attached image. Also I attached result for number 1 and 2 using the same type
![PHOTO_20190331_114345](https://user-images.githubusercontent.com/1650425/55288200-e8b1f300-53ab-11e9-8d3c-e3fa2548ec8b.jpg)
![PHOTO_20190331_114301](https://user-images.githubusercontent.com/1650425/55288201-e8b1f300-53ab-11e9-8e7d-5542c071c6a5.jpg)
![PHOTO_20190331_114225](https://user-images.githubusercontent.com/1650425/55288202-e8b1f300-53ab-11e9-9d0d-018719539550.jpg)


 of code.

**Comment by c-schmitz** [comment]
Looks great. 
Keep on looking  I had a hard time with this, too - at some point in time you will probably slap yourself because usually it is something like a very simple small mistake in code that completely kills the animations.

Do you have a repository with your fork? (for a later pull request)

**Comment by BaltasarParreira** [comment]
I can make a fork, but right now since there is nothing not even 10% working with your library I don't think is worth.
Anyway for the correct display on this cube, If I send arrays of other dimensions to it, an incomprehensible “porridge” will be displayed. 
Secondly, as we noted above, one element of type char has a size of 1 byte (8 bits). If we conditionally divide the cube into vertical columns, in each of which there are 8 LEDs, then we get 64 columns, or 64 bytes, in each of which there are 8 bits (8 LEDs). I found that if I want to light up the 1st front left line (all vertical leds of that line)  the array position is this:
buffer[63] = 0xff; // all leds binary B11111111

So I just need to figure out how to convert/map your x + y + z to my array[column number] = leds to be on (0x00 to 0xff max), right?

**Comment by MajicDesigns** [comment]
Closed due to lack of activity

**Comment by ImanCol** [comment]
Hello, I just bought this cube with the same code that you shared. It has been very difficult to make animations because I do not fully understand the data that is being sent in pCube, nor because it adds the [i] to it, I have also tried to know how that "[i]" works, but I only managed to obtain these dates:

pCube [(61)] = 0x01; // 61 equals the LED in the lower column that will light.

I have also tried to understand the reverse cascade code "pCube [i] << = 1;" but I have not had many results.

I only managed to make animations with the code "pCube [(61)] = 0x01;" where I change the 61 to turn on the LEDs that I want and raise them with "pCube [i] << = 2; I still don't understand how those values ​​are stored in" pCube ", I try to print in the console but it outputs data from boxes without Format.

Also try using Arduinoblock, a Blocky based platform, because it is a project that I should use with Scracth, but most of them lack operators or are very limited. At least this one had the command "Serial.write", but this only allows sending byte (Decimals), so I have only been able to send the data of Open Menu, Open command and Exit.
If there is someone who can share more information, I would appreciate it.

**Comment by MajicDesigns** [comment]
The [i] is an ARRAY SUBSCRIPT. Sound like you need to read up and understand how arrays work in C++.
<< is the LEFT SHIFT operator. Again, this is standard C++.

The rest of your message I don't understand. Perhaps someone else will.

**Comment by ImanCol** [comment]
By the way. I was testing the example files inside the Example folder of MD_Cubo and the only one that reacted with the cube was "MD_Cubo_Text_Scrolling". Although I try to insert a text in the command section, I don't take any action. I was looking in the .ino file for the code "0xAD", which is the one that runs to communicate with the Arduino through the serial port, but I didn't find any, not even the piece of code "Serial.write (0xAD);"

![image](https://user-images.githubusercontent.com/26169049/89585771-16ab1100-d804-11ea-976d-024fb11b4a96.png)

![image](https://user-images.githubusercontent.com/26169049/89585779-19a60180-d804-11ea-890e-a87d9afda2e9.png)

![image](https://user-images.githubusercontent.com/26169049/89585867-3e01de00-d804-11ea-906d-8934f8b4c8c3.png)


![image](https://user-images.githubusercontent.com/26169049/89586036-90db9580-d804-11ea-9348-07e6d33fa570.png)
"Serial.write (0xAD);" // Keep the Serial port open to communicate with Arduino.

Serial.write (0xf2); // Open the command to send the animation code "Serial.write (p, COLUMN_COUNT);" (part that I have not been able to decipher because I see byte

Serial.write (0xED); // Exit Arduino Mode

COLUMN_COUNT is a public variable with a value of 64.
p is an abbreviation of pCube where all the intinerated code has been stored.


By the way, I found this Issues from Google because I was looking for "MD_CUBE + Zirrfa", after consulting the next page.

https://majicdesigns.github.io/MD_Cubo/page_z_i_f_f_r_a_d_i_y4x4x4.html

The cube they mention on that page has the same MCU (stc15f2k60s2)

Try to use a Software called LD8

https://github.com/tomazas/ledcube8x8x8
https://github.com/tomazas/DotMatrixJava

I was reading your post about this program, and I did not find references about this chip, because it tells me that it only supports the MCU STC12C5A60S2. Strange because it looks a lot like the screenshots on the MD_Cube page about Zirffa.

Anyway, I would really like to be able to make a decent animation. My niece needs this to put it in her class the other week ...

**Comment by ImanCol** [comment]
I was disassembling the code and managed to hit the trick.

I have made a more understandable code where I simplify the animation process a bit
[https://gist.github.com/ImanCol/2dd04de4de5303bc2131fe57fda70d62#file-arduino_3dcube_control-ino](url)
You can see the instructions on how it works (Spanish)
https://paste2.org/GBjnIhpL
